name: Binaries-manual-MIPS
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: catalinii/minisatip-build-image:latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Build MIPS
      run: |
       ./configure --disable-netcv --enable-static --host=mipsel-linux-musl CC="zig cc -target mipsel-linux-musl -static"
       make EXTRA_CFLAGS="-I/sysroot/mipsel/include -L/sysroot/mipsel/lib" EMBEDDED=1
       zip -9 -r /minisatip_mips.zip minisatip html

    - name: Archive built binaries
      uses: actions/upload-artifact@v4
      with:
        name: minisatip
        path: |
          /minisatip_mips.zip
